import Head from 'next/head'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Bettingsite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <div className='grid grid-cols-4'>
    <Sidebar/>
    </div>
    {/* Featured */}
    {/* Footer */}
    </div>
  )
};
